<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LATR-PERTYNYBEK" ignored="2" name="Command line test" tests="2" failures="1" timestamp="25 Nov 2019 16:25:05 GMT" time="9.035" errors="0">
  <testcase name="loginTest1" time="1.372" classname="com.webace.tests.EmployeeLoginTest.EmployeeLoginTest"/>
  <testcase name="negativeLoginTest1" time="0.675" classname="com.webace.tests.EmployeeLoginTest.EmployeeLoginTest">
    <failure type="java.lang.AssertionError" message="expected [Invalid login. Please try again.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Invalid login. Please try again.] but found []
at com.webace.tests.EmployeeLoginTest.EmployeeLoginTest.negativeLoginTest1(EmployeeLoginTest.java:44)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- negativeLoginTest1 -->
  <testcase name="@BeforeTest testSetup" time="0.0" classname="com.webace.utilities.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest testSetup -->
  <testcase name="@AfterTest tearDownTest" time="0.0" classname="com.webace.utilities.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest tearDownTest -->
</testsuite> <!-- Command line test -->
